version: "3.9"

services:
  backend:
    build:
      context: ../../apps/backend-py
    ports:
      - "8000:8000"

  tools-go:
    build:
      context: ../../services/tools-go
    ports:
      - "8080:8080"

  web:
    build:
      context: ../../apps/web
    ports:
      - "3000:3000"
